#pragma once

#define CAN_SHOULDER_QUATERNION 0x20
#define CAN_SHOULDER_ACCELEROMETER 0x21
#define CAN_SHOULDER_GYROSCOPE 0x22
#define CAN_SHOULDER_ACCURACY 0x23
#define CAN_SHOULDER_SET_YZ_DEGREE 0x24

#define SDA_PIN 0
#define SCL_PIN 1
#define INT_PIN 10
#define RST_PIN 2
#define SHOULDER_Z_PIN 8
#define SHOULDER_Y_PIN 3
#define RX_PIN 4
#define TX_PIN 5

