#pragma once

#include <map>

#ifndef DEG_TO_RAD
  #define DEG_TO_RAD  0.0174532925199433f
#endif

#ifndef RAD_TO_DEG
  #define RAD_TO_DEG  57.29577951308233f
#endif

#define CAN_SHOULDER_SET_YZ_DEGREE 0x01
#define CAN_ELBOW_SET_Y_DEGREE 0x02
#define CAN_WRIST_SET_YZ_DEGREE 0x03
#define CAN_SHOULDER_SET_ROTATE_RADIAN 0x04
#define CAN_ELBOW_SET_ROTATE_RADIAN 0x05
#define CAN_WRIST_SET_ROTATE_RADIAN 0x06
#define CAN_CLAW_SET_XZG_DEGREE 0x07

#define CAN_PLATFORM_QUATERNION 0x10
#define CAN_PLATFORM_ACCELEROMETER 0x11
#define CAN_PLATFORM_GYROSCOPE 0x12
#define CAN_PLATFORM_ACCURACY 0x13
#define CAN_PLATFORM_BAROMETER 0x14

#define CAN_SHOULDER_QUATERNION 0x20
#define CAN_SHOULDER_ACCELEROMETER 0x21
#define CAN_SHOULDER_GYROSCOPE 0x22
#define CAN_SHOULDER_ACCURACY 0x23
#define CAN_SHOULDER_STATUSES 0x24
#define CAN_SHOULDER_FIRMWARE_UPGRADE 0x27
#define CAN_SHOULDER_FIRMWARE_UPGRADE_CONFIRMED 0x28

#define CAN_ELBOW_QUATERNION 0x30
#define CAN_ELBOW_ACCELEROMETER 0x31
#define CAN_ELBOW_GYROSCOPE 0x32
#define CAN_ELBOW_ACCURACY 0x33
#define CAN_ELBOW_STATUSES 0x34
#define CAN_ELBOW_FIRMWARE_UPGRADE 0x37
#define CAN_ELBOW_FIRMWARE_UPGRADE_CONFIRMED 0x38

#define CAN_WRIST_QUATERNION 0x40
#define CAN_WRIST_ACCELEROMETER 0x41
#define CAN_WRIST_GYROSCOPE 0x42
#define CAN_WRIST_ACCURACY 0x43
#define CAN_WRIST_STATUSES 0x44
#define CAN_WRIST_FIRMWARE_UPGRADE 0x47
#define CAN_WRIST_FIRMWARE_UPGRADE_CONFIRMED 0x48

#define CAN_CLAW_QUATERNION 0x50
#define CAN_CLAW_ACCELEROMETER 0x51
#define CAN_CLAW_GYROSCOPE 0x52
#define CAN_CLAW_ACCURACY 0x53
#define CAN_CLAW_STATUSES 0x54
#define CAN_CLAW_HEIGHT 0x55
#define CAN_CLAW_RANGE 0x56
#define CAN_CLAW_FIRMWARE_UPGRADE 0x57
#define CAN_CLAW_EULER_AND_HEIGHT 0x58
#define CAN_CLAW_FIRMWARE_UPGRADE_CONFIRMED 0x58

#define MEMS_SDA_PIN 0
#define MEMS_SCL_PIN 1
#define MEMS_INT_PIN 10
#define MEMS_RST_PIN 2
#define MEMS_RX_PIN 0
#define MEMS_TX_PIN 1

#define WITMOTION_XSHUT_PIN 6
#define WITMOTION_INT_PIN 7
#define VL_6180X_SHUT_PIN 13
#define VL_53LOX_SHUT_PIN 14

#define MEMS_UART_ID uart0
#define DETECTORS_SDA_PIN 2
#define DETECTORS_SCL_PIN 3

#define SHOULDER_Z_PIN 9
#define SHOULDER_Y_PIN 3
#define ELBOW_Y_PIN 3
#define WRIST_Z_PIN 9
#define WRIST_Y_PIN 3
#define CLAW_X_PIN 8
#define CLAW_Y_PIN 9
#define CLAW_Z_PIN 10
#define CLAW_GRIPPER_PIN 11
#define CAN_RX_PIN 4
#define CAN_TX_PIN 5
#define CAN_SEND_LOOP_TIMEOUT 50
#define CAN_SEND_WAIT_TIMEOUT 50
#define CAN_SEND_ATTEMPTS 3
#define CAN_RECEIVE_HASH_CAPACITY 256
#define INVALID_CAN_ID 0xFFFFFFFF
#define CAN_RECEIVE_LOOP_TIMEOUT 50
#define CAN_RECEIVE_WAIT_TIMEOUT 50
#define IMU_WAIT_TIMEOUT 50
#define IMU_NO_DATA_TIMEOUT 500
#define ENGINE_TASK_LOOP_TIMEOUT 50

#define RANGE_SHORT_TO_LONG_THRESHOLD 180
#define RANGE_LONG_TO_SHORT_THRESHOLD 150
#define RANGE_INVALID_READING 8191
#define RANGE_LOOP_TIMEOUT 100
#define RANGE_SWITCH_TIMEOUT 50
#define RANGE_SENSOR_STABILIZE_DELAY 10

#define VL53_DEFAULT_ADDR 0x29
#define VL618_DEFAULT_ADDR 0x29

#define VL53_NEW_ADDR 0x2A
#define VL618_NEW_ADDR 0x2B

#define SERVO_MAX_DEGREE_CHANGE 0.5f
#define SERVO_MIN_DEGREE_CHANGE 0.1f

#define SHOULDER_Z_HOME_POSITION 135
#define SHOULDER_Y_HOME_POSITION 90
#define ELBOW_Y_HOME_POSITION 90
#define WRIST_Z_HOME_POSITION 90
#define WRIST_Y_HOME_POSITION 90
#define CLAW_X_HOME_POSITION 135
#define CLAW_Z_HOME_POSITION 90
#define CLAW_GRIPPER_HOME_POSITION 30

#define IMU_ANGLE_FILTER 0.1f
#define SERVO_DEAD_ZONE 2.0f